# POST http://localhost:9001/api/projects/predict
POST https://teekoivi.users.cs.helsinki.fi/api/projects/predict
Accept: application/json
Content-Type: application/json

{
    "nameWithOwner":"phil-lavin/Trustico-PHP"
}